inventories/development/hosts
Does not work because of missing host `datapass` (default host name in
Vagrantfile) in inventories.
The error message:
```
[WARNING: Could not match supplied host pattern, ignoring: datapass
ERROR! Specified hosts and/or --limit does not match any hosts
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.]
```
=> chore: Harden vagrant datapass provisionning

.github/workflows/build.yml
The aim is to speed up the deployments.
The CI job tests that the code is valid with the `lint` and `test` scripts, then builds the frontend files and creates a downloadable archive exposed as a Github action artifact.
Two artifacts are built, one for the staging environment, one for the production environment.
Theses two environments differ by the env variable that are injected in the bundle, to control the external urls the bundled app calls when run from a browser.
Once this PR is merged, the deployment scripts can be updated in order to retrieve the artifacts when deploying the frontend application.
=> Build frontend in CI

configure.yml, deploy.yml, roles/react-app/tasks/main.yml, roles/react-app/templates/server.conf.j2, roles/react-app/templates/service.conf.j2, scripts/deploy-dev.sh, scripts/deploy-server-app.sh, scripts/deploy-static-app.sh, signup-front/signup-front.conf
Now that Github actions bundles up the frontend into action artifacts, these artifacts can be downloaded to be deployed right away on the desired environement.
The script uses two new ansible variables that will be defined in the secrets repository:
- `github_access_token`: a token with the `public_repo` scope, needed to download the artifacts
- `target_deploy_env`: one of `staging` or `production`, will determine which build artifact is used on the environement
=> Deploy frontend from github action artifacts

.github/workflows/build.yml
Piwik was not working anymore since the Github Action build feature.
This is due to bad env var names, CRA requires variables to start with `REACT_APP_`, the faulty names started with `REACT_`.
=> Fix piwik integration

.github/workflows/back.yml
Readd some basic checks for lint/security (no more GA because of strange issues), at least it fails the backend CI with these checks
=> chore: add simple linter/security checker in back CI

.github/workflows/manual-deployment.yml
In order to be able to manually trigger a deployment, there must be a workflow to run to trigger a webhook call from Github to the application server.
=> [feature] Manual deployment workflow

configure.yml, roles/continuous-deployment/defaults/main.yml, roles/continuous-deployment/handlers/main.yml, roles/continuous-deployment/tasks/main.yml, roles/continuous-deployment/templates/webhook.service.j2, roles/continuous-deployment/templates/webhooks.json.j2, roles/ufw/tasks/main.yml
Now that the frotend assets are built automatically, it is time to move to the next step and setup a continuous deployment workflow.
The aim is to use Github webhooks in order to react to the repository events and deploy applications when necessary.
By installing [a webhook utility](https://github.com/adnanh/webhook) on the servers, one can react to Github events, and detect when it is time to run the deployment scripts.
The tool runs as an http server listening on port 9000.
The trafic does **not** need to be encrypted with HTTPS since the github events payloads are public, and it would be tedious to run the webhook utility behind a reverse proxy (but still possible).
- on Github: to use the webhook utility, one must setup a [webhook](https://github.com/betagouv/datapass/settings/hooks) …
=> [feat] Continuous deployment

.github/workflows/continuous-deployment.yml, configure.yml
The deployment is failing because no deployment SSH key gets accepted on the different environments.
- there was an issue with the private key being saved in the current directory, don't know why
- after this change, the staging frontend deployment key was still being rejected:
- after a small investigation, I noticed that on the staging env, where there should be two deployment ssh keys (frontend and backend), only the frontend was present
- I first thought it was because of the `all` hosts selector in the `configure.yml` playbook, which led to resolve only one host and thus one group (the first matching one, `datapass-back`), taking only into account the `datapass-back.yml` var file
- To verify this hypothesis, I ran the playbook with a more specific host selector, `datapass-front`. …
=> Fix deployment

signup-back/app/models/enrollment/api_entreprise.rb, signup-front/src/pages/ApiEntreprise/demarches.json, signup-front/src/pages/ApiEntreprise/index.js
j'ai repris #274 de @DorineLam.
Je n'ai pas bien compris l'utilité de `technical_team_type` vu que ça ne se modifie pas avec les formulaires pré-remplis ; je l'ai donc supprimé. C'est gênant mais pas bloquant pour le moment.
C'est testé en local.
J'ai refait la PR car je crois que le CI sur les fork ne marche pas.
Ajout des formulaires pré-remplis de : 
- e-Attestations
- Provigis
- Achat-solution
=> API Entreprise ajout des editeurs

signup-back/app/bridges/hubee_portail_dila_bridge.rb, signup-back/app/models/enrollment/hubee_portail_dila.rb, signup-back/app/policies/enrollment/hubee_portail_dila_policy.rb, signup-back/config/data_providers.yml, signup-front/src/components/organisms/form-sections/hubee-sections/DemarcheEnLigneSection.js, signup-front/src/config/data-provider-parameters.tsx, signup-front/src/pages/HubeePortail.js, signup-front/src/pages/HubeePortailDila.js
Création du fichier du formulaire HubEE Dila. Quelques changements restent à faire, ils sont listés dans le ticket Trello mais je les remets ici : 
- "En quoi consiste cette démarche ?" devient "En quoi consiste ces démarches ?"
- Le contenu de ce cadre est :
"- AEC - Acte d'Etat Civil : Ce service donne la possibilité aux usagers d'effectuer sur internet leurs demandes d'actes de naissance, de mariage, de décès.
- DDPACS - Démarche en ligne de préparation à la conclusion d’un Pacs : Ce service permet à des usagers souhaitant se pacser de compléter en ligne les informations nécessaires à cette union (actuellement contenues dans les Cerfa) et de télécharger leurs pièces justificatives (actes de naissance convention spécifique de PACS le cas échéant). L'ensemble est envoyé à la commune …
=> Creation form hubee dila

frontend/src/Routes.js, frontend/src/components/organisms/FormRouter.js, frontend/src/components/templates/Form/index.js, frontend/src/components/templates/hooks/use-list-item-navigation.ts
Add a noScroll state in useEffect() callback -> template/form/index.js to prevent scrolling if forms are incomplete / get errors.
=> feat: Prevent form to scroll when errors in Form completion.

frontend/src/components/atoms/Helper/index.js, frontend/src/components/atoms/Helper/style.css, frontend/src/pages/DgfipPages/api-impot-particulier-common.js
when content text is wider than 140 characters
an helper-large class is add to adjust helper tooltip to min-width to 350px.
=> add class to helper tooltip

frontend/src/index.tsx
See Sentry Docs https://docs.sentry.io/platforms/javascript/guides/react/configuration/filtering/
Find this solution from https://stackoverflow.com/questions/61651440/prevent-sentry-io-from-logging-server-error-codes
Regex flag mi standing for:
'm': multiline mode
'i': case insensitive
More Details about Regex Flag here : https://javascript.info/regexp-introduction
=> FixBug/sentry - Ignore 401 errors

frontend/src/pages/ApiEntreprise/index.js
Fait suite à la sortie de la V3 et du nouveau site.
Il y a besoin de changer les liens vers les documentations qui sont désormais cassés.
=> Propose de changer les liens et les labels

backend/app/notifiers/api_particulier_notifier.rb, backend/spec/acceptances/api_particulier_bridge_with_notifier_spec.rb, backend/spec/rails_helper.rb, backend/spec/support/devise_request_login_helpers.rb
First step of a long migration from API Particulier infra to API Entreprise. This commit implements only a webhook for the validate event, which adds the token id to the payload in order to keeps old token and new token linked thanks to this id.
`API_PARTICULIER_WEBHOOK_URL` has to be set to https://entreprise.api.gouv.fr/api/datapass/api_particulier/webhook
and `API_PARTICULIER_VERIFY_TOKEN` has to be set to the value already set on `API_ENTREPRISE_VERIFY_TOKEN`
=>     feat: API Particulier implements webhooks to API Entreprise backend

frontend/src/pages/ApiEntreprise/demarches.json, frontend/src/pages/ApiEntreprise/index.js
SETEC n'est pas un éditeur à proprement parler, mais ils peuvent déployer des versions du logiciels d'Atexo pour le compte de leurs clients et le gère en leur nom.
=> Add SETEC form

backend/app/policies/enrollment/api_indemnisation_pole_emploi_policy.rb, backend/app/policies/enrollment/api_statut_demandeur_emploi_policy.rb
Add double quote instead of single quote
=> Fix linter for rubocop dependabots 

backend/app/models/enrollment.rb, backend/spec/controllers/enrollments/export_spec.rb, backend/spec/models/enrollment_spec.rb
This pull request introduces:
* Some basic tests on export functionalities
* A bugfix on json attributes (which were ruby hash printed)
* type key for team_members_json
=> Add team member type to export for enrollments

frontend/src/pages/ApiEntreprise/demarches.json, frontend/src/pages/ApiEntreprise/index.js
Cette PR ajoute : 
- le formulaire pré-rempli pour le cas d'utilisation Portail GRU
- le formulaire pré-rempli pour le cas d'utilisation spécifique des éditeurs
- la bonne url vers la page cas d'usage car actuellement ça renvoit une 404
A vérifier avant de merger : 
J'ai ajouté pas mal de texte dans les descriptions des formulaires pré-remplis, j'ai normalement mis des retours à la ligne mais je ne peux pas voir moi-même le résultat.
=> Ajoute formulaires Spécifique aux éditeurs et Portail GRU

frontend/src/components/organisms/Header.js
=> Remplacement du texte du header Datapass

frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.js
https://trello.com/c/LjVeYyoP/1624-etq-u-sur-une-liste-d%C3%A9v%C3%A9nements-dune-habilitation-je-vois-la-date-de-cr%C3%A9ation-de-l%C3%A9v%C3%A9nement-et-non-sa-date-de-mise-%C3%A0-jour
=> Display `created_at` instead of `updated_at` in Enrollment's events list

backend/app/controllers/application_controller.rb, backend/app/mailers/rgpd_mailer.rb, backend/app/services/enrollment_email_templates_retriever.rb, backend/spec/services/enrollment_email_templates_retriever_spec.rb, frontend/public/index.html, frontend/src/components/atoms/Loader/index.js, frontend/src/components/organisms/ErrorBoundaryFallback.js, frontend/src/components/organisms/Nav.js, frontend/src/components/templates/Faq.tsx, frontend/src/lib/__snapshots__/process-event.test.js.snap, frontend/src/lib/index.js, frontend/src/lib/index.test.js
Supression de contact@api.gouv.fr du produit, remplacé par datapass@api.gouv.fr
=> Remplacement de l'email de contact Datapass

backend/app/models/enrollment.rb, backend/app/policies/enrollment_policy.rb
Refacto `enrollment_policy`
- an administrator could in future have access to enrollment with an archived status. 
- change `default_scope -> { where.not(status: "archived") }` as it prevents us to have access to enrollments with an archive status in console.
=> this is now handle with the `class Scope`
Refacto `state event transition`
=> HotFix Archive PR

frontend/src/index.tsx
Pour utiliser la nouvelle instance de sentry, il faut que le build front de DataPass integre la nouvelle adresse.
=> chore: use new sentry instance

backend/app/models/enrollment.rb, backend/app/policies/enrollment_policy.rb, backend/spec/controllers/enrollments/change_state_spec.rb
instructor and administrator can no longer archive a validated enrollment. enrollment has to be revoked before.
https://user-images.githubusercontent.com/43042737/229558005-e373ddca-02bb-4dc5-aa4c-8c501192d892.mov
=> cant not archive a validated enrollment

frontend/src/components/molecules/QuickViewList/EnrollmentQuickView.tsx, frontend/src/components/molecules/QuickViewList/styles.css, frontend/src/components/templates/InstructorHome.tsx
Bugs are listed below :
- si j'ai sélectionné des API dans la page Accueil et que je clique sur "Toutes mes habilitations à instruire" ou "Tous mes messages non lus", mon choix est visible dans la page Tableau
- Pas de marge supplémentaire au-dessus du titre de l'habilitation si je n'ai pas le badge Nouveau
- Si l'habilitation n'a pas le badge Nouveau, le titre n'est pas en gras
=> Fix some UI bugs on the new Instructor Homepage 🤕

backend/db/migrate/20230510091641_fix_archive_cron_damages.rb, backend/db/schema.rb
Petite explication du correctif à l'attention d'@Isalafont :
**_Contexte du problème :_**
- Le CRON (user 0) a archivé des habilitations par erreur.
- Activation déployée le 7 Mars à 9:43.
- Désactivation déployée le 15 Mars à 18:11.
_**Résolution du problème :**_
Raphaël et moi avons convenu que supprimer simplement les archivages effectués par le CRON malveillant avant la date du 20 Mars (la désactivation a eu lieu le 15 au soir, mais par sécurité nous avons préféré laisser une marge) et restaurer les statuts des habilitations concernées à leur état précédent, pourrait facilement réinitialiser la situation.
En effet, en restaurant ces habilitations à leur état d'origine, elles seront à nouveau sujettes au CRON d'archivage qui, cette fois, est correct.
Le seul petit inconvénient de cette …
=> Fix Archive CRON Damages 💥

frontend/src/components/molecules/QuickViewList/EnrollmentQuickView.tsx
Use back navigation instead of sending the user to home page if no location state.
=> Go Back To Enrollments Button Fix 🤕

backend/app/models/team_member.rb, backend/db/migrate/20230523081445_clean_phone_numbers_in_team_members.rb, backend/db/schema.rb, backend/spec/models/enrollment_spec.rb
**Description du bug** : @SchweisguthN a signalé un problème étrange. Les numéros de téléphone du Délégué à la protection des données (DPD) sont refusés sur le formulaire Captchetat. Le bug a été constaté sur l'habilitation spécifique à l'URL https://datapass.api.gouv.fr/api-captchetat/52062#head. Nicolas a également essayé en environnement de staging et n'a pas pu soumettre une demande, rencontrant la même erreur.
**Actions effectuées** : Après avoir examiné le problème, j'ai constaté que l'utilisateur avait saisi des caractères invisibles dans le numéro de téléphone. Pour résoudre ce problème, un nettoyage a été ajouté à la validation du numéro de téléphone, supprimant tous les caractères non numériques. De plus, une migration a été créée pour nettoyer les numéros de téléphone existants …
=> Sanitize `phone_number` for Team Members 📞

backend/config/data_providers.yml
Cette API retire le scope `mesri_identifiant` qui renvoyait l'INE.
Il a été décidé de supprimer ce périmètre car la donnée renvoyée ne provient pas du FD mais est celle présente en paramètre d'appel dans le cas de l'utilisation de la modalité d'appel INE.
Ce champ n'a donc pas d'intérêt pour l'usager.
=> [API Particulier] Retire le scope mesri_identifiant

backend/app/models/enrollment/api_r2p_unique.rb, backend/app/policies/enrollment/api_ficoba_sandbox_policy.rb, backend/app/policies/enrollment/api_ficoba_unique_policy.rb, backend/app/policies/enrollment/api_impot_particulier_sandbox_policy.rb, backend/app/policies/enrollment/api_impot_particulier_unique_policy.rb, backend/app/policies/enrollment/api_r2p_sandbox_policy.rb, backend/app/policies/enrollment/api_r2p_unique_policy.rb, backend/app/policies/enrollment/api_sfip_sandbox_policy.rb, backend/app/policies/enrollment/api_sfip_unique_policy.rb, backend/app/policies/enrollment/unique_policy.rb, backend/app/policies/enrollment_policy.rb, backend/spec/controllers/enrollments/update_spec.rb, backend/spec/factories/enrollments.rb
Dans les classes Enrollment::UniquePolicy et Enrollment::ApiR2pUniquePolicy, lors de l'ajout de nouvelles valeurs à la clé :additional_content, nous utilisions concat pour ajouter une nouvelle entrée au tableau d'attributs, créant ainsi une nouvelle clé à chaque fois plutôt que de mettre à jour la clé existante.
Pour résoudre ce problème, j'ai introduit une méthode utilitaire appelée augment_permitted_attributes. Cette méthode prend en entrée un tableau d'attributs, une clé et de nouvelles valeurs à ajouter. Elle recherche d'abord si le tableau d'attributs contient déjà une clé correspondante. Si c'est le cas, elle met à jour la valeur de cette clé en ajoutant les nouvelles valeurs. Sinon, elle ajoute une nouvelle entrée au tableau avec la clé et les nouvelles valeurs.
=> Fix augment permitted attributes in policies

backend/config/application.rb, backend/config/environments/test.rb, backend/config/initializers/frontal.rb, backend/config/initializers/frontal_mailer.rb
Will be override in deployment, in order to not deliver daily emails defined in scheduler (like API Parteprise site)
Related https://github.com/etalab/admin_api_entreprise/commit/90ca749024fcd590bd44b32780c45734b3a74108
=> Introduce ENV FRONTAL for ops

frontend/src/components/atoms/ExternalRedirect/index.tsx, frontend/src/components/organisms/FormRouter.tsx
L'objectif est de rediriger l'utilisateur vers DS lorsqu'il accède au formulaire de l'API TP.
Le code vérifie d'abord si l'API mentionnée dans l'URL correspond à l'API TP. Ensuite, il cherche la présence d'un `enrollmentId` dans cette même URL. Si un `enrollmentId` est détecté, cela signifie que l'utilisateur se trouve sur le détail d'une habilitation API TP déjà établie. Dans une telle situation, il est essentiel de permettre à l'utilisateur de maintenir son accès.
=> Redirect to demarches simplifiées on API TP form routing

backend/Gemfile, backend/Gemfile.lock, backend/app/controllers/documents_controller.rb, backend/app/models/document.rb, backend/app/models/document/pdf_document.rb, backend/app/models/document/spreadsheet_document.rb, backend/app/policies/document_policy.rb, backend/app/serializers/admin_user_serializer.rb, backend/app/serializers/application_serializer.rb, backend/app/serializers/document_serializer.rb, backend/app/serializers/enrollment_email_template_serializer.rb, backend/app/serializers/enrollment_hubee_validated_serializer.rb, backend/app/serializers/enrollment_serializer.rb, backend/app/serializers/event_serializer.rb, backend/app/serializers/full_user_serializer.rb, backend/app/serializers/light_enrollment_serializer.rb, backend/app/serializers/public_enrollment_list_serializer.rb, backend/app/serializers/team_member_serializer.rb, backend/app/serializers/team_member_with_profile_serializer.rb, backend/app/serializers/user_enrollment_list_serializer.rb, backend/app/serializers/user_serializer.rb, backend/app/serializers/webhook_enrollment_serializer.rb, backend/app/serializers/webhook_event_serializer.rb, backend/app/serializers/webhook_user_with_profile_serializer.rb, backend/app/services/magic_validator.rb, backend/app/uploaders/document_uploader.rb, backend/config/brakeman.ignore, backend/config/initializers/carrierwave.rb, backend/config/routes.rb
Storing files on server is not a good practice for a lot of reasons.
This pull request introduces a S3 storage backend for documents, which has replication by design, which makes it resilient.
Some changelogs:
* Recycle old documents route (which is not use by the frontend) to mirror/mask the actual cloud storage url
* Some refactor for content validation (not the same way to read content between file and s3 with carrierwave, dunno why)
* Scout clean with `ApplicationSerializer`
=> Use cloud storage for documents

backend/app/mailers/enrollment/api_particulier_mailer.rb, backend/app/notifiers/api_particulier_notifier.rb, backend/app/views/enrollment/api_particulier_mailer/validate_for_responsable_technique.text.erb, backend/spec/notifiers/api_particulier_notifier_spec.rb
The email is skipped if the responsable technique and the demandeur are the same user.
=> API Particulier: send email to responsable technique on validation

frontend/src/components/molecules/AlertMissingPhoneNumber/index.tsx, frontend/src/components/molecules/SoftAlert/index.css, frontend/src/components/molecules/SoftAlert/index.tsx, frontend/src/components/templates/Form/index.tsx
Suite aux discussions dans ce ticket : https://linear.app/pole-api/issue/DAT-160/etq-u-si-je-nai-pas-renseigne-de-numero-de-telephone-dans-mcp-je-vois
=> Restrict demandeur phone_number check only on first Form render

backend/config/data_providers/api_particulier.yml
- Ajoute un S à études
- Remonte le scope de l'identité de l'étudiant boursier plus haut pour uniformiser avec les autres API
=> Fix typo scopes API particulier

backend/app/notifiers/abstract_entreculier_notifier.rb, backend/spec/notifiers/abstract_entreculier_notifier_spec.rb
Copy from BaseNotifier the `notify` method, for 2 reasons:
1. This event handles mailbox messages, which was ignored in the ApiEntreculierNotifier
2. The `notify` event is useless for API Entreculier
=> Bugfix mailbox for API Entreculier

frontend/src/components/molecules/EnrollmentCard/index.tsx
Ne va pas sur la page de snapshot quand l'enrollment n'est pas reopened
=> Doesnt consult snapshot when habilitation isnt reopened

backend/app/models/enrollment.rb
Some bridge needs events creation (🤷), so we change the order (all after_transition)
1. Create an event
2. Create the snapshot
3. Triggers the bridge
Previously the bridge was in a before_transition, which is not logical
=> Change callbacks order on state machine enrollment

backend/app/models/enrollment.rb, backend/app/policies/enrollment_policy.rb, backend/app/services/abstract_enrollments_extractor.rb, backend/spec/controllers/enrollments/create_spec.rb, backend/spec/controllers/enrollments/update_spec.rb, backend/spec/services/abstract_enrollments_extractor_spec.rb, backend/spec/services/enrollments_extractor/to_remind_before_archive_spec.rb
Do not allow actions on migrated data
1. Introduce Enrollment.migrated_target_apis
2. No more create/update on enrollments
3. No more reminder on these migrated target APIs
=> Lock migrated API from v1 to v2 actions

frontend/src/components/organisms/form-sections/DonneesSection/index.tsx
Suite aux retours de Nicolas https://linear.app/pole-api/issue/DAT-398/etq-u-je-vois-le-meme-affichage-de-documentation-pour-api-ip-et-api#comment-d0dd61fa
=> Feature/dat-398 etq u je vois le meme affichage de documentation pour API IP FC et API SFIP

backend/app/models/enrollment.rb
- Avoid frontend to broke if a "demandeur" has an enrollment for mon compte pro in his home page.
=> QuickFix when user has a mon compte pro enrollment in his homepage

backend/app/models/enrollment.rb
We can have team member with non-downcase email, users have downcased email.
Closes https://errors.data.gouv.fr/organizations/sentry/issues/147486
=> Harden Enrollment#set_company_info

backend/app/services/api_sirene.rb, backend/spec/services/api_sirene_spec.rb
The user or the FD can access these informations: first one is logged in with this organization, the later is an administration.
No need to filter non diffusible organizations here.
=> API INSEE: remove diffusible filter
