roles/ruby/tasks/main.yml
Run command:
```
ansible-playbook ./configure.yml --tag ruby --inventory=./inventories/development
```
=> chore: Add ruby 2.7.3 to role rbenv->rubies

configure.yml, roles/rails-app/handlers/main.yml, roles/rails-app/tasks/main.yml, roles/rails-app/templates/server.conf.j2, roles/rails-app/templates/sidekiq.service.j2, scripts/deploy-dev.sh, scripts/deploy.sh
Related https://github.com/betagouv/signup-back/pull/264
=> Introduce sidekiq service for datapass (signup-back)

signup-front/README.md, signup-front/src/Routes.js, signup-front/src/components/molecules/ContactTable.tsx, signup-front/src/components/organisms/Footer.js, signup-front/src/components/organisms/Header.js, signup-front/src/components/templates/Faq.css, signup-front/src/components/templates/Faq.tsx, signup-front/src/lib/api.js, signup-front/src/pages/AidantsConnect.js, signup-front/src/pages/ApiEntreprise/index.js, signup-front/src/pages/ApiParticulier/index.js, signup-front/src/pages/FranceConnect.js, signup-front/src/pages/Hubee/index.js, signup-front/src/pages/LeTaxiChauffeurs.js, signup-front/src/pages/LeTaxiClients.js
Hello, 
Comme convenu une chouette petite PR pour avoir des commits a mon nom :D 
Fonctionnalités
- Il suffit de remplir l'objet `questions`
- tu peux renseigner une ancre dans l’url et ca ouvre la question correspondante
=> Create a FAQ page

signup-front/src/components/organisms/form-sections/DonneesSection/Scopes.js, signup-front/src/pages/ApiEntreprise/index.js
> ETQ demandeur, je vois une pop-in d'avertissement lorsque je sélectionne certains scopes du formulaire API Entreprise
=> Adding modal for API Entreprise sensitive data

signup-front/src/Routes.js, signup-front/src/config/data-provider-parameters.js, signup-front/src/pages/ApiPrestationsSociales.js
Ici le datapass stand alone (front). 
@rdubigny : tu peux déployer si c'est ok + créer le datapass France Connect
=> create datapass stand-alone prestations sociales

configure.yml
=> Revert "Mailjet for auth api"

signup-back/docs/webhooks.md
Il y avait des coquilles dans la documentation des webhooks. Il me semble que c'est sans impact pour API Entreprise. @skelz0r je te laisse approve cette PR pour m'indiquer que c'est bien le cas ✌🏻
=> doc: update webhook documentation

signup-front/src/pages/ApiParticulier/demarches.json, signup-front/src/pages/ApiParticulier/index.js
=> Revert "Feature: Hide PoleEmploi scopes from API Particulier from"

signup-front/src/config/data-provider-parameters.tsx
=> Revert "fix: temporary add old api ingres to remove admin rights"

frontend/src/pages/LeTaxi.js
=> Revert "Test caching rules with a build trigger"

frontend/src/components/molecules/NewEnrollmentButton/index.tsx
=> Revert "feat: remove link to DILA form"

backend/app/views/enrollment_mailer/hubee_portail/create.text.erb, backend/app/views/enrollment_mailer/hubee_portail/submit.text.erb
Ajout des modifs de mails oubliées dans la branche précédente
=> Modifs mails certdc

backend/app/views/enrollment_mailer/api_tiers_de_prestation/submit.text.erb
réduit le texte, change la hiérarchie de l'information, ajoute 3 emojis (dont 2 qui ne sont pas formatés correctement on dirait)
=> new email format

backend/app/views/enrollment_mailer/hubee_portail/refuse.text.erb, backend/app/views/enrollment_mailer/hubee_portail/request_changes.text.erb, backend/app/views/enrollment_mailer/hubee_portail/validate.text.erb, backend/app/views/enrollment_mailer/hubee_portail_dila/refuse.text.erb, backend/app/views/enrollment_mailer/hubee_portail_dila/request_changes.text.erb, backend/app/views/enrollment_mailer/hubee_portail_dila/validate.text.erb
Version du 25 mars (après des changements précédents)
=> MAJ mails HubEE

backend/config/data_providers.yml, frontend/src/config/data-provider-parameters.tsx
Changement suite mail de Laetitia
=> Modif mails HubEE 08/04

frontend/src/pages/ApiEntreprise/demarches.json
Ajout du formulaire pré-rempli MGDIS
=> API Entreprise : add editor MGDIS

README.md, frontend/src/components/templates/Login/index.js
Add Hubee_portail_dila as a service in Welcome Page
=> Update Hubee portail dila welcome page

frontend/src/components/organisms/form-sections/DemarcheSection/index.js, frontend/src/components/organisms/form-sections/DescriptionSection.js
Des petits tirets manquants pour uniformisation
=> Correction orthographe

README.md, backend/Dockerfile
Compatible with with macbook pro M1
=> Docker installation up and running

frontend/src/pages/ApiEntreprise/index.js
J'ai repéré deux petits manques dans les labels de la liste de données API Entreprise.
Cette MR propose de les corriger
=> Fix erreur de label - liste des données

frontend/src/lib/index.js
more info: https://github.com/axios/axios/issues/4655
=> fix: network error is not detected anymore after updating axios

frontend/src/pages/ApiEntreprise/demarches.json
=> API Ent: Fix key name

frontend/src/App.css, frontend/src/components/molecules/ExpandableQuote/style.css, frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.css, frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.js
=> Revert "Feat/message design feed"

frontend/src/App.css, frontend/src/components/molecules/ExpandableQuote/style.css, frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.css, frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.js
This reverts commit 6e07ce33b3a59611f829a4294b97fb3a294baf16.
=> Revert "Revert "Feat/message design feed""

backend/Gemfile.lock
Fix standardrb to pass rubocop linter test
update json gem version
=> Fix standardrb

backend/app/models/enrollment.rb, backend/app/serializers/light_enrollment_serializer.rb, frontend/src/App.css, frontend/src/components/templates/InstructorEnrollmentList.js, frontend/src/components/templates/PublicEnrollmentList.js, frontend/src/components/templates/enrollmentListStyle.js
=> Add column to count messages

backend/app/views/enrollment_mailer/api_cpr_pro_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_e_contacts_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_e_pro_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_ficoba_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_hermes_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_impot_particulier_fc_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_impot_particulier_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_infinoe_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_mire_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_ocfi_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_opale_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_r2p_sandbox/validate.text.erb, backend/app/views/enrollment_mailer/api_robf_sandbox/validate.text.erb
Modification de certains mails, ajout de ceux manquants jusqu'ici.
=> Modification des mails de validation des habilitations sandbox

backend/app/mailers/enrollment_mailer.rb, backend/app/views/enrollment_mailer/admin/notification_email_to_instructors.text.erb, backend/spec/mailers/enrollment_mailer_spec.rb
=> add demandeur name and email in notif_email_to_instructor template.

backend/db/migrate/20220914100157_remove_demarches.rb, backend/db/schema.rb, frontend/src/pages/ApiParticulier/demarches.json
Dédoublonnage de 2 modèles pré-remplis, suite à la PR #665.
A ne pas merger tant qu'on n'a pas décidé quoi faire des demandes passés avec ces modèles ici supprimés.
=> Dédoublonnage modèles pré-remplis

backend/app/views/enrollment_mailer/api_tiers_de_prestation/submit.text.erb
Ajout de la mention de la récence du RIB (en espérant que ça soit lu)
=> Update submit.text.erb - Modif mail Submit URSSAF

backend/spec/models/enrollment_spec.rb
Checks valid existing states in Enrollment model
=> Prevent bug from State Machine

frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.js
=> instructor: Open mail icon when message have been marked as processed

frontend/src/components/templates/UserEnrollmentList/index.js
Prevent null  message to create error boundary : cannot read properti…es of null (readind 'message')
https://sentry.data.gouv.fr/organizations/sentry/issues/680/?project=8&query=is%3Aunresolved
=> senty error : null message / state.message 

backend/app/mailers/enrollment_mailer.rb, backend/spec/mailers/enrollment_mailer_spec.rb
**1st step :**
Change in backend contact email with a no_reply "notifications@api.gouv.fr"
=> email : change contact@api.gouv.fr into notifications@api.gouv.fr

frontend/src/pages/FranceConnect.js
- update cadre juridique
Link to zip file does not work properly / the zip file is not downloaded when clicking on it.
=> update cadre juridique FC

backend/app/notifiers/api_entreprise_notifier.rb
Supp notify_subscribers_by_email_for_submitted_enrollment from all files
=> HotFix notify_subscribers_by_email_for_submitted_enrollment from all files

backend/app/views/enrollment_mailer/api_satelit_production/validate.text.erb, backend/app/views/enrollment_mailer/api_satelit_sandbox/validate.text.erb, backend/config/data_providers.yml
forget to add template validate email for DGFIP satelit sandbox and production
=> HotFix : Api satelit sandbox -production email validate template

backend/app/models/enrollment.rb
=> Amelioration export CSV

backend/app/mailers/enrollment_mailer.rb, backend/app/models/enrollment_email_template.rb, backend/app/serializers/enrollment_email_template_serializer.rb, backend/app/services/enrollment_email_templates_retriever.rb, backend/app/views/enrollment_mailer/franceconnect/validate.text.erb, backend/spec/controllers/enrollments_email_templates_controller_spec.rb
Add scopes in validate template email for api `franceconnect`
Add tests.
**After Review :**
=> Feat/ demadeur api fc scopes in email for demandeurs

frontend/src/pages/ApiEntreprise/index.js
Ajout de la section disant que c'est OK sans texte de loi pour l'OpenData
=> Add exception for public data

.github/workflows/frontend-build.yml
=> Revert "Update frontend-build.yml"

frontend/src/components/templates/Admin/index.js
=> change wording for forbidden access page admin

frontend/src/components/atoms/hyperTexts/Badge.css, frontend/src/components/atoms/hyperTexts/Badge.tsx, frontend/src/components/templates/InstructorEnrollmentList.tsx
https://trello.com/c/ELumHLMf/1638-etq-instructeur-je-vois-les-nouveaux-designs-de-badges-sur-la-page-de-liste-des-habilitations
=> Round Badge 🔵

frontend/src/pages/ApiEntreprise/demarches.json
=> Supprime formulaire pré-remplissage et ajoute Portail GRU - instruction

backend/app/views/enrollment_mailer/hubee_portail/request_changes.text.erb
+ ajout d'une mention demandée par Agnès de la DGS
=> Correction orthographe mail HubEE

frontend/src/components/atoms/inputs/FieldsetWrapper.js, frontend/src/components/molecules/MultiSelect/index.js
https://trello.com/c/BA38cYQ9/1643-etq-i-je-peux-naviguer-sur-les-champs-fournisseur-et-statut-au-clavier
=> `MultiSelect` Accessibility ♿️

frontend/src/pages/AgentConnectFi.js, frontend/src/pages/AgentConnectFs.js
=> Modification du cadre juridique prérempli formulaires Agent Connect

backend/app/mailers/enrollment_mailer.rb, backend/app/mailers/webhook_mailer.rb, backend/app/views/webhook_mailer/fail.text.erb, backend/spec/mailers/webhook_mailer_spec.rb
=> Remplacement de l'adresse de contact technique

README.md, frontend/src/App.css
Hello @SchweisguthN ,
Le header passe par dessus le contenu de la page sur les petits écrans.
Je corrigeais se bug sur MonComptePro, j'en profite pour le corriger sur DataPass aussi.
Avant : 
Après : 
Je te laisse approuver la PR si ok pour toi ?
=> feat: fix header display

backend/app/policies/enrollment/api_droits_cnam_policy.rb, frontend/src/pages/ApiDroitsCnam.js
Remove the following scopes as no longer required : 
- `cnam_beneficiaires`
- `cnam_contrats`
- `cnam_caisse`
- `cnam_exonerations`
- `cnam_medecin_traitant`
- `cnam_presence_medecin_traitant`
Replace them with the following scope as required true : 
- `droits_assurance_maladie`
=> api droits_cnam / remove scopes

backend/app/controllers/enrollments_controller.rb, backend/app/controllers/users_controller.rb, backend/config/brakeman.ignore, backend/spec/controllers/users_controller_spec.rb, frontend/src/components/organisms/Table/index.tsx, frontend/src/components/organisms/Table/style.css, frontend/src/components/templates/Admin/UserList/index.js, frontend/src/services/users.js
**Backend**
- Add pagination to user index controller
- Refacto some variable to call pagination in backend
- Include a filter logic in User Index method to apply it to frontend.
- Add Rspec tests.
**Frontend** 
- connect pagination from backend to frontend
- add filter parameters
⚠️  Still need to correct the behaviour of the board when a short "filter" is apply in email filter
=> Pagination server side for user list (admin view) 🙌🏻

backend/app/controllers/data_provider_configurations_controller.rb, backend/config/data_providers.yml, frontend/src/components/molecules/NextStepButton/index.tsx, frontend/src/components/templates/UserEnrollmentList/Enrollment.css, frontend/src/components/templates/UserEnrollmentList/Enrollment.js, frontend/src/config/data-provider-configurations.tsx
Add next step button for validated enrolments.
=> Next Step Button ➡️

backend/app/controllers/application_controller.rb, backend/app/models/enrollment.rb, backend/app/policies/enrollment_policy.rb, backend/config/locales/fr.yml, backend/spec/controllers/enrollments/copy_spec.rb, frontend/src/components/templates/CopyEnrollment.js
More precise and detailed copy error messages.
=> Copy error messages ⚠️

backend/config/data_providers.yml
PR suivant la précédente, j'avais raté un truc bizarre dans la description du projet
=> Changement description modele qiis

backend/app/models/enrollment.rb, backend/app/models/enrollment/hubee_portail.rb, backend/app/models/enrollment/hubee_portail_dila.rb, backend/spec/controllers/enrollments/change_state_spec.rb
Organisation it will raises a new error
=> case hubee with status validated already exists in Commune

backend/app/bridges/hubee_portail_bridge.rb
Action pour (espérer) supprimer les erreurs 400 constatées
=> Suppression enrollmentId

frontend/src/components/molecules/Dropdown/style.css, frontend/src/components/templates/InstructorHome.css
=> multiselect dropdown content display with right auto instead of 0

frontend/src/config/scope-warning-modal-configuration.tsx, frontend/src/pages/ApiEntreprise/index.js
fix https://github.com/betagouv/datapass/issues/464
Avec juste 1 petite année de retard
=> popup warning effectifs

backend/config/data_providers.yml
Cette PR modifie la bulle d'aide aux choix des données et ajoute des helpers pour certaines données
=> [API Particulier] Modifie bulle d'aide "choix des données"

backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb, backend/db/schema.rb
This PR is linked to [[API Entreprise] évolution de la gestion des droits #1044](https://github.com/betagouv/datapass/pull/1044). 
See this comment with the api entreprise modifications in order to help to write the migration : 
https://github.com/betagouv/datapass/pull/1044#issuecomment-1578151472
---
_Before Migration :_ 
---
_After Migration_
=> Add a migration to rename scopes for api_entreprise

frontend/src/pages/ApiEntreprise/demarches.json
Related https://support.etalab.gouv.fr/#ticket/zoom/60899
=> API Entreprise: update cas d'usages links

frontend/src/components/organisms/form-sections/ÉquipeSection/Contact.js
fix #1119 
@DorineLam tu me dis ce que tu en penses
=> [UX] better info box

.github/workflows/frontend-build.yml
App is on 2 differents servers now
=> CI: frontend build works for multiple staging

backend/app/policies/enrollment/api_impot_particulier_sandbox_policy.rb, backend/spec/controllers/enrollments/create_spec.rb, backend/spec/factories/enrollments.rb
Closes https://errors.data.gouv.fr/organizations/sentry/issues/3957/
=> Bugfix Enrollment::ApiImpotParticulierSandboxPolicy invalid scopes permission

backend/app/policies/enrollment/api_impot_particulier_unique_policy.rb, backend/app/policies/enrollment/api_sfip_sandbox_policy.rb, backend/app/policies/enrollment/api_sfip_unique_policy.rb
Same as 72a45eedd93b31bcf43c5028391bf048b0d636c4
=> Bugfix all API Impot particulier permitted scopes

backend/app/policies/enrollment/api_ficoba_sandbox_policy.rb, backend/app/policies/enrollment/api_ficoba_unique_policy.rb
Same as 72a45eedd93b31bcf43c5028391bf048b0d636c4
Closes https://errors.data.gouv.fr/organizations/sentry/issues/3990/
=> Bugfix ficoba policies

.github/workflows/frontend-build.yml
Prepare to introduce a new sandbox datapass
=> CI: Build artefacts for sandbox

frontend/src/pages/ApiEntreprise/index.tsx
À ne pas merger avant : https://github.com/etalab/siade/pull/869
=> Ajout de Qualifelec dans le label Open Data

.github/workflows/frontend-build.yml
Prepare to intoduce a new production datapass
=> CI: Build artefacts for production

backend/app/policies/enrollment/api_entreprise_policy.rb, frontend/src/pages/ApiEntreprise/demarches.json, frontend/src/pages/ApiEntreprise/index.tsx
Première fois que je fais ça, j'espère ne rien avoir oublié
@DorineLam Vu que tu connais bien les cas d'usage peux-tu check mes ajouts dans le fichier `frontend/src/pages/ApiEntreprise/demarches.json` (formulaires pré-remplis) , j'ai mis par défaut `false` partout mais peut-être qu'un formulaire pré-remplis veut ce scope.
API-774
=> Add Qualiopi France Compétences scope for API Entreprise

backend/db/schema.rb
Related https://github.com/betagouv/datapass/commit/f88bfd14fbe8dfd35cc51d3dcf40e96c3dcc3498
=> Add missing schema.rb from migration

backend/app/models/concerns/dgfip_validation_methods.rb, frontend/src/components/organisms/form-sections/dgfip-sections/HomologationSecuriteSection.tsx
Pour MEP avant de remettre les modifs
=> Ecrasement bloc homologation à nouveau

backend/app/models/concerns/dgfip_validation_methods.rb, frontend/src/components/organisms/form-sections/dgfip-sections/HomologationSecuriteSection.tsx
=> Changement blocs homologation

backend/app/models/enrollment.rb
Closes https://errors.data.gouv.fr/organizations/sentry/issues/4744/
=> Enrollment.data_retention_period validation

backend/spec/controllers/enrollments/update_spec.rb
Ref https://linear.app/pole-api/issue/DAT-113/etq-u-de-webhook-je-recois-une-notification-des-quun-evenement-a-lieu
=> Test that notifier is trigger on enrollment update

backend/app/models/enrollment.rb
Closes https://errors.data.gouv.fr/organizations/sentry/issues/5155/
Related bd8444a9dce667b21a6b530cc347ce994e7f288e
=> Bugfix Enrollment#copy with s3 documents

backend/app/controllers/ping_controller.rb, backend/config/routes.rb, backend/spec/controllers/ping_controller_spec.rb
=> Introduce ping controller

backend/app/models/enrollment.rb, backend/app/models/opinion.rb, backend/app/models/opinion_comment.rb, backend/db/migrate/20231013154315_create_opinions.rb, backend/db/migrate/20231016131627_create_opinion_comments.rb, backend/db/schema.rb, backend/spec/factories/opinion_comments.rb, backend/spec/factories/opinions.rb, backend/spec/models/opinion_comment_spec.rb, backend/spec/models/opinion_spec.rb
Part 1/3 of opinions backend
2 models:
* Opinion
* OpinionComment
Related https://linear.app/pole-api/issue/DAT-138/conception-technique-backend
=> DAT-138- Introduce opinion models

backend/app/services/data_provider_configurations.rb, backend/spec/services/data_provider_configurations_spec.rb
Ref https://mattermost.incubateur.net/betagouv/pl/p83cmc67178jpnyw9nmc17oe8e
=> Interpolate erb within data providers configurations

backend/app/mailers/enrollment_mailer.rb, backend/spec/mailers/enrollment_mailer_spec.rb
Closes https://errors.data.gouv.fr/organizations/sentry/issues/131123/
=> Bugfix EnrollmentMailer#notify_support_franceconnect

backend/app/controllers/application_controller.rb, backend/app/controllers/enrollments_controller.rb, backend/app/models/enrollment.rb, backend/app/policies/enrollment_policy.rb, backend/config/locales/fr.yml, backend/spec/controllers/enrollments/copy_spec.rb, backend/spec/models/enrollment_spec.rb
- model : validation -> Add a scope condition in enrollment model to exclude copied enrollment with status archived
- modification for policy
- add test but will need review to optimize it
=> can create an enrollment copy if previous copy has been archived

backend/app/views/enrollment_mailer/agent_connect_fi/validate.text.erb, backend/app/views/enrollment_mailer/agent_connect_fs/validate.text.erb
Changement du template de message de base pour les validations de datapass pour agentconnect en y intégrant notre adresse email.
=> update validate text fro agentconnect

backend/app/models/enrollment.rb, backend/app/services/spreadsheet_generator.rb, backend/spec/services/spreadsheet_generator_spec.rb
Have to harden `validated_at` method for enrollments without validated events.
=> Add validated_at to SpreadsheetGenerator

backend/app/models/enrollment.rb, backend/spec/services/spreadsheet_generator_spec.rb
=> Harden SpreadsheetGenerator#updated_at by returning the right value

backend/app/models/enrollment/api_infinoe_production.rb, backend/app/policies/enrollment/api_infinoe_production_policy.rb, frontend/src/pages/DgfipPages/ApiInfinoeProduction.tsx
=> Feature/dat-282 Suppression du bloc homologation + Ajout par défaut du cadre juridique pour API INFINOE Production

frontend/src/App.css, frontend/src/components/templates/UserEnrollmentList/index.tsx
=> Fix: Display changes_requested enrollments on UserEnrollmentsList

frontend/src/App.css
And use the same as UserEnrollmentList changes_requested background card
=> Change background color from Instructor Enrollment List with DSFR Color

backend/app/services/api_sirene.rb, backend/spec/support/api_insee_payload_helpers.rb
=> Change Sirene API url

frontend/src/components/organisms/form-sections/DonneesSection/index.tsx
=> DAT-353 - Change date to hide AccessMode API IP sandbox and API IP Unique

backend/config/data_providers/api_particulier.yml, backend/spec/controllers/validated_enrollment_snapshots_controller_spec.rb, frontend/src/components/atoms/inputs/FieldsetWrapper.tsx
fix https://linear.app/pole-api/issue/API-1129/modifier-le-datapass
=> Add API Particulier CNAV Prestations scopes

frontend/src/pages/DgfipPages/ApiInfinoeSandbox.tsx, frontend/src/pages/DgfipPages/common.tsx
=> Change rgpd additionnal terms of use without homologation for Api Infinoe sandbox only

backend/config/data_providers/api_particulier.yml
A corriger également coté SIADE
=> corrections scopes APIs Prestation

backend/app/bridges/api_captchetat_bridge.rb
This reverts commit 1a63e0e73287d5a181b68c029f187ecd11f32b64.
=> Revert "Changement api_name bridge Captchetat (#1492)"

backend/app/bridges/api_captchetat_bridge.rb
A ne pas merger avant le 4 juin
Reverts betagouv/datapass#1501
=> Revert "Revert "Changement api_name bridge Captchetat (#1492)"" 

backend/config/data_providers/api_particulier.yml
Ajout nouvel éditeur (pour FS pilotes FQF)
=> Ajout éditeur Agedi

frontend/src/pages/DgfipPages/api-impot-particulier-common.tsx
=> Suppression des modèles pré-remplis SVAIR

backend/app/policies/concerns/dgfip_policy_methods.rb, frontend/src/pages/DgfipPages/ApiR2PSandbox.tsx
- En attente de confirmation de la DGFiP pour l'ID definitif
=> Add 2 new accessMode id to r2p unique and sandbox form

backend/app/policies/concerns/dgfip_policy_methods.rb, frontend/src/pages/DgfipPages/ApiFicobaProduction.tsx, frontend/src/pages/DgfipPages/ApiFicobaSandbox.tsx, frontend/src/pages/DgfipPages/ApiFicobaUnique.tsx
Reverts betagouv/datapass#1546
=> Revert "Feature/dat 716 modification des scopes et ajout de modeles pre remplis dans"

backend/config/data_providers/others.yml
=> Add missing providers key in others.yml file for api_rial

backend/app/models/concerns/dgfip_validation_methods.rb, backend/app/models/enrollment/api_rial_sandbox.rb, backend/app/policies/concerns/dgfip_policy_methods.rb, backend/app/policies/enrollment/api_rial_sandbox_policy.rb, frontend/src/pages/DgfipPages/api-rial-sandbox.tsx
Reverts betagouv/datapass#1556
=> Revert "Feature/dat 768 api rial ajout de cas dusage"

frontend/src/pages/DgfipPages/ApiFicobaSandbox.tsx
=> scope value was missing from a group
